### ISSUE TITLE
Provide a command-line tool chain

### ISSUE THREAD

**Issue by kevinbirch** [OutbreakInc/Galago#3]
It would be great if there was also a command-line tool chain available, or at least instructions on how to assemble one yourself.  I would like to manage my source code and project files myself and use my preferred editor instead of a web browser.

**Comment by kuym** [comment]
Done, check it out in the [Getting Started Guide](https://github.com/OutbreakInc/Galago/wiki/Getting-started-guide).

**Comment by timsavage** [comment]
I'd ask for something similar or at least to have the command being executed echoed out during compilation. I would like to be able to use standard Make+gcc tool chain along with the normal IDE for development.

I've hacked something together with Geany and custom commands but it's not that same as an IDE (of which linux already has many that sit on top of gdb).
