### ISSUE TITLE
Can't run/debug the default program

### ISSUE THREAD

**Issue by bugmeister** [OutbreakInc/Galago#5]
I'm on Windows 7, I've install the Logiblock platform, downloaded the arm sdk, installed python27 for x86. The program has been correctly built from what I see. 
I'm invoking the following command in one prompt :

```
node <logiblock-path>/bin/SDK.js --install 
```

It tells me:

"Device 'Galago' (serial number '01DN') attached, available to debug with gdb command: 
target remote localhost:1033

```
-> Running gdb server; press ctrl+z, enter (end-of-file) to exit."
```

Then in another prompt, I start gdb, try to connect to the galago device with :

```
"target remote localhost:1033"
```

Then after a few second, I got this message in my first prompt :

```
"Driver terminated unexpectedly!"
```

What I'm doing wrong ?

Thanks for any help you might give me :)

**Comment by kuym** [comment]
Moved to https://github.com/OutbreakInc/LogiblockPlatform/issues/1
